### ISSUE TITLE
Showing Gray When Also Blue

### ISSUE THREAD

**Issue by shishkabibal** [dado3212/message-indicator#1]
Pretty nifty SIMBL plugin!

Any reason why you decided to show the gray indicator while there is a blue indicator? It seems a little redundant to me, because there is no way to have an unseen message (blue) but have already replied to it (not gray).

Maybe the blue indicator should just turn gray upon viewing a message (and then go away completely when you reply).

**Comment by dado3212** [comment]
You could make it so that was the case, but it didn't behave well with stuff like Do Not Disturb mode.  The reason I wanted both was mainly for consistencies sake.  It's open source though, so it'd be pretty easy to fork and change it so that it's not there while the message is also unread.
